package com.wujiabo.feather.system.standard.domain;

import java.io.Serializable;
import java.util.Date;

public class TSysOperLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.log_id
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private Long logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.title
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.business_type
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private Integer businessType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.method
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.request_method
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String requestMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.operator_type
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private Integer operatorType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.oper_name
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String operName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.oper_url
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String operUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.oper_ip
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String operIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.oper_location
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String operLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.oper_param
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String operParam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.json_result
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String jsonResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.status
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.error_msg
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String errorMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.oper_time
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private Date operTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.del_flag
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.create_by
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.create_time
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.update_by
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.update_time
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_oper_log.remark
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.log_id
     *
     * @return the value of t_sys_oper_log.log_id
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.log_id
     *
     * @param logId the value for t_sys_oper_log.log_id
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.title
     *
     * @return the value of t_sys_oper_log.title
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.title
     *
     * @param title the value for t_sys_oper_log.title
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.business_type
     *
     * @return the value of t_sys_oper_log.business_type
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public Integer getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.business_type
     *
     * @param businessType the value for t_sys_oper_log.business_type
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setBusinessType(Integer businessType) {
        this.businessType = businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.method
     *
     * @return the value of t_sys_oper_log.method
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.method
     *
     * @param method the value for t_sys_oper_log.method
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.request_method
     *
     * @return the value of t_sys_oper_log.request_method
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getRequestMethod() {
        return requestMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.request_method
     *
     * @param requestMethod the value for t_sys_oper_log.request_method
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setRequestMethod(String requestMethod) {
        this.requestMethod = requestMethod == null ? null : requestMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.operator_type
     *
     * @return the value of t_sys_oper_log.operator_type
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public Integer getOperatorType() {
        return operatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.operator_type
     *
     * @param operatorType the value for t_sys_oper_log.operator_type
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setOperatorType(Integer operatorType) {
        this.operatorType = operatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.oper_name
     *
     * @return the value of t_sys_oper_log.oper_name
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getOperName() {
        return operName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.oper_name
     *
     * @param operName the value for t_sys_oper_log.oper_name
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setOperName(String operName) {
        this.operName = operName == null ? null : operName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.oper_url
     *
     * @return the value of t_sys_oper_log.oper_url
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getOperUrl() {
        return operUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.oper_url
     *
     * @param operUrl the value for t_sys_oper_log.oper_url
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setOperUrl(String operUrl) {
        this.operUrl = operUrl == null ? null : operUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.oper_ip
     *
     * @return the value of t_sys_oper_log.oper_ip
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getOperIp() {
        return operIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.oper_ip
     *
     * @param operIp the value for t_sys_oper_log.oper_ip
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setOperIp(String operIp) {
        this.operIp = operIp == null ? null : operIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.oper_location
     *
     * @return the value of t_sys_oper_log.oper_location
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getOperLocation() {
        return operLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.oper_location
     *
     * @param operLocation the value for t_sys_oper_log.oper_location
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setOperLocation(String operLocation) {
        this.operLocation = operLocation == null ? null : operLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.oper_param
     *
     * @return the value of t_sys_oper_log.oper_param
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getOperParam() {
        return operParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.oper_param
     *
     * @param operParam the value for t_sys_oper_log.oper_param
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setOperParam(String operParam) {
        this.operParam = operParam == null ? null : operParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.json_result
     *
     * @return the value of t_sys_oper_log.json_result
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getJsonResult() {
        return jsonResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.json_result
     *
     * @param jsonResult the value for t_sys_oper_log.json_result
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setJsonResult(String jsonResult) {
        this.jsonResult = jsonResult == null ? null : jsonResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.status
     *
     * @return the value of t_sys_oper_log.status
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.status
     *
     * @param status the value for t_sys_oper_log.status
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.error_msg
     *
     * @return the value of t_sys_oper_log.error_msg
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.error_msg
     *
     * @param errorMsg the value for t_sys_oper_log.error_msg
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg == null ? null : errorMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.oper_time
     *
     * @return the value of t_sys_oper_log.oper_time
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public Date getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.oper_time
     *
     * @param operTime the value for t_sys_oper_log.oper_time
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setOperTime(Date operTime) {
        this.operTime = operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.del_flag
     *
     * @return the value of t_sys_oper_log.del_flag
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.del_flag
     *
     * @param delFlag the value for t_sys_oper_log.del_flag
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.create_by
     *
     * @return the value of t_sys_oper_log.create_by
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.create_by
     *
     * @param createBy the value for t_sys_oper_log.create_by
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.create_time
     *
     * @return the value of t_sys_oper_log.create_time
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.create_time
     *
     * @param createTime the value for t_sys_oper_log.create_time
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.update_by
     *
     * @return the value of t_sys_oper_log.update_by
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.update_by
     *
     * @param updateBy the value for t_sys_oper_log.update_by
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.update_time
     *
     * @return the value of t_sys_oper_log.update_time
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.update_time
     *
     * @param updateTime the value for t_sys_oper_log.update_time
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_oper_log.remark
     *
     * @return the value of t_sys_oper_log.remark
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_oper_log.remark
     *
     * @param remark the value for t_sys_oper_log.remark
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", logId=").append(logId);
        sb.append(", title=").append(title);
        sb.append(", businessType=").append(businessType);
        sb.append(", method=").append(method);
        sb.append(", requestMethod=").append(requestMethod);
        sb.append(", operatorType=").append(operatorType);
        sb.append(", operName=").append(operName);
        sb.append(", operUrl=").append(operUrl);
        sb.append(", operIp=").append(operIp);
        sb.append(", operLocation=").append(operLocation);
        sb.append(", operParam=").append(operParam);
        sb.append(", jsonResult=").append(jsonResult);
        sb.append(", status=").append(status);
        sb.append(", errorMsg=").append(errorMsg);
        sb.append(", operTime=").append(operTime);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}