package com.wujiabo.feather.system.standard.domain;

import java.io.Serializable;
import java.util.Date;

public class TSysLoginLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_login_log.log_id
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private Long logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_login_log.user_name
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_login_log.ipaddr
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String ipaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_login_log.login_location
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String loginLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_login_log.browser
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String browser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_login_log.os
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String os;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_login_log.status
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_login_log.msg
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_login_log.login_time
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_login_log.del_flag
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_login_log.create_by
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_login_log.create_time
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_login_log.update_by
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_login_log.update_time
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_login_log.remark
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_login_log
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_login_log.log_id
     *
     * @return the value of t_sys_login_log.log_id
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_login_log.log_id
     *
     * @param logId the value for t_sys_login_log.log_id
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_login_log.user_name
     *
     * @return the value of t_sys_login_log.user_name
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_login_log.user_name
     *
     * @param userName the value for t_sys_login_log.user_name
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_login_log.ipaddr
     *
     * @return the value of t_sys_login_log.ipaddr
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getIpaddr() {
        return ipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_login_log.ipaddr
     *
     * @param ipaddr the value for t_sys_login_log.ipaddr
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setIpaddr(String ipaddr) {
        this.ipaddr = ipaddr == null ? null : ipaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_login_log.login_location
     *
     * @return the value of t_sys_login_log.login_location
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getLoginLocation() {
        return loginLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_login_log.login_location
     *
     * @param loginLocation the value for t_sys_login_log.login_location
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setLoginLocation(String loginLocation) {
        this.loginLocation = loginLocation == null ? null : loginLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_login_log.browser
     *
     * @return the value of t_sys_login_log.browser
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_login_log.browser
     *
     * @param browser the value for t_sys_login_log.browser
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setBrowser(String browser) {
        this.browser = browser == null ? null : browser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_login_log.os
     *
     * @return the value of t_sys_login_log.os
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_login_log.os
     *
     * @param os the value for t_sys_login_log.os
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setOs(String os) {
        this.os = os == null ? null : os.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_login_log.status
     *
     * @return the value of t_sys_login_log.status
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_login_log.status
     *
     * @param status the value for t_sys_login_log.status
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_login_log.msg
     *
     * @return the value of t_sys_login_log.msg
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_login_log.msg
     *
     * @param msg the value for t_sys_login_log.msg
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_login_log.login_time
     *
     * @return the value of t_sys_login_log.login_time
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_login_log.login_time
     *
     * @param loginTime the value for t_sys_login_log.login_time
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_login_log.del_flag
     *
     * @return the value of t_sys_login_log.del_flag
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_login_log.del_flag
     *
     * @param delFlag the value for t_sys_login_log.del_flag
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_login_log.create_by
     *
     * @return the value of t_sys_login_log.create_by
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_login_log.create_by
     *
     * @param createBy the value for t_sys_login_log.create_by
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_login_log.create_time
     *
     * @return the value of t_sys_login_log.create_time
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_login_log.create_time
     *
     * @param createTime the value for t_sys_login_log.create_time
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_login_log.update_by
     *
     * @return the value of t_sys_login_log.update_by
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_login_log.update_by
     *
     * @param updateBy the value for t_sys_login_log.update_by
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_login_log.update_time
     *
     * @return the value of t_sys_login_log.update_time
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_login_log.update_time
     *
     * @param updateTime the value for t_sys_login_log.update_time
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_login_log.remark
     *
     * @return the value of t_sys_login_log.remark
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_login_log.remark
     *
     * @param remark the value for t_sys_login_log.remark
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_login_log
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", logId=").append(logId);
        sb.append(", userName=").append(userName);
        sb.append(", ipaddr=").append(ipaddr);
        sb.append(", loginLocation=").append(loginLocation);
        sb.append(", browser=").append(browser);
        sb.append(", os=").append(os);
        sb.append(", status=").append(status);
        sb.append(", msg=").append(msg);
        sb.append(", loginTime=").append(loginTime);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}