package com.wujiabo.feather.system.standard.mapper;

import com.wujiabo.feather.system.standard.domain.TSysRole;
import com.wujiabo.feather.system.standard.domain.TSysRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    long countByExample(TSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int deleteByExample(TSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int insert(TSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int insertSelective(TSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    List<TSysRole> selectByExample(TSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    TSysRole selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int updateByExampleSelective(@Param("record") TSysRole record, @Param("example") TSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int updateByExample(@Param("record") TSysRole record, @Param("example") TSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int updateByPrimaryKeySelective(TSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int updateByPrimaryKey(TSysRole record);
}