package com.wujiabo.feather.system.standard.mapper;

import com.wujiabo.feather.system.standard.domain.TSysUser;
import com.wujiabo.feather.system.standard.domain.TSysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    long countByExample(TSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int deleteByExample(TSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int insert(TSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int insertSelective(TSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    List<TSysUser> selectByExample(TSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    TSysUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int updateByExampleSelective(@Param("record") TSysUser record, @Param("example") TSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int updateByExample(@Param("record") TSysUser record, @Param("example") TSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int updateByPrimaryKeySelective(TSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int updateByPrimaryKey(TSysUser record);
}