package com.wujiabo.feather.system.standard.mapper;

import com.wujiabo.feather.system.standard.domain.TSysLoginLog;
import com.wujiabo.feather.system.standard.domain.TSysLoginLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSysLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_login_log
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    long countByExample(TSysLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_login_log
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    int deleteByExample(TSysLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_login_log
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    int deleteByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_login_log
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    int insert(TSysLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_login_log
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    int insertSelective(TSysLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_login_log
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    List<TSysLoginLog> selectByExample(TSysLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_login_log
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    TSysLoginLog selectByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_login_log
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    int updateByExampleSelective(@Param("record") TSysLoginLog record, @Param("example") TSysLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_login_log
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    int updateByExample(@Param("record") TSysLoginLog record, @Param("example") TSysLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_login_log
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    int updateByPrimaryKeySelective(TSysLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_login_log
     *
     * @mbg.generated Wed Feb 03 14:24:51 CST 2021
     */
    int updateByPrimaryKey(TSysLoginLog record);
}