package com.wujiabo.feather.system.standard.mapper;

import com.wujiabo.feather.system.standard.domain.TSysRolePerms;
import com.wujiabo.feather.system.standard.domain.TSysRolePermsExample;
import com.wujiabo.feather.system.standard.domain.TSysRolePermsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSysRolePermsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_perms
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    long countByExample(TSysRolePermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_perms
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int deleteByExample(TSysRolePermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_perms
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int deleteByPrimaryKey(TSysRolePermsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_perms
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int insert(TSysRolePerms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_perms
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int insertSelective(TSysRolePerms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_perms
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    List<TSysRolePerms> selectByExample(TSysRolePermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_perms
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    TSysRolePerms selectByPrimaryKey(TSysRolePermsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_perms
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int updateByExampleSelective(@Param("record") TSysRolePerms record, @Param("example") TSysRolePermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_perms
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int updateByExample(@Param("record") TSysRolePerms record, @Param("example") TSysRolePermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_perms
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int updateByPrimaryKeySelective(TSysRolePerms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_perms
     *
     * @mbg.generated Tue Feb 02 16:08:52 CST 2021
     */
    int updateByPrimaryKey(TSysRolePerms record);
}